apiVersion: v1
kind: Service
metadata:
  name: coach5g-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: coach5g-frontend
    app.kubernetes.io/name: coach5g
spec:
  selector:
    app: coach5g-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
