// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: capture.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Packet is a single decoded network packet from a capture session.
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SrcIp         string                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         string                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Length        uint32                 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	Info          string                 `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	Raw           []byte                 `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty"`
	InterfaceName string                 `protobuf:"bytes,10,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PodName       string                 `protobuf:"bytes,11,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,12,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Node          string                 `protobuf:"bytes,13,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Packet) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *Packet) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Packet) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Packet) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Packet) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Packet) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Packet) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Packet) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Packet) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Packet) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Packet) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Packet) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// PacketBatch is a batch of packets from one capture session.
type PacketBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packets       []*Packet              `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PodIp         string                 `protobuf:"bytes,3,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketBatch) Reset() {
	*x = PacketBatch{}
	mi := &file_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketBatch) ProtoMessage() {}

func (x *PacketBatch) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketBatch.ProtoReflect.Descriptor instead.
func (*PacketBatch) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{1}
}

func (x *PacketBatch) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *PacketBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketBatch) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

// SubscribeRequest asks the api-server to fan out packets for a session.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *SubscribeRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SubscribeRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

// Ack is the response to StreamPackets.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// TsharkRequest asks capture-agent to enable/disable tshark for a session.
type TsharkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsharkRequest) Reset() {
	*x = TsharkRequest{}
	mi := &file_capture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsharkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsharkRequest) ProtoMessage() {}

func (x *TsharkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsharkRequest.ProtoReflect.Descriptor instead.
func (*TsharkRequest) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{4}
}

func (x *TsharkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TsharkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsharkResponse) Reset() {
	*x = TsharkResponse{}
	mi := &file_capture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsharkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsharkResponse) ProtoMessage() {}

func (x *TsharkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsharkResponse.ProtoReflect.Descriptor instead.
func (*TsharkResponse) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{5}
}

func (x *TsharkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_capture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_capture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_capture_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_capture_proto protoreflect.FileDescriptor

const file_capture_proto_rawDesc = "" +
	"\n" +
	"\rcapture.proto\x12\n" +
	"capture.v1\"\xdd\x02\n" +
	"\x06Packet\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06length\x18\a \x01(\rR\x06length\x12\x12\n" +
	"\x04info\x18\b \x01(\tR\x04info\x12\x10\n" +
	"\x03raw\x18\t \x01(\fR\x03raw\x12%\n" +
	"\x0einterface_name\x18\n" +
	" \x01(\tR\rinterfaceName\x12\x19\n" +
	"\bpod_name\x18\v \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\f \x01(\tR\tnamespace\x12\x12\n" +
	"\x04node\x18\r \x01(\tR\x04node\"q\n" +
	"\vPacketBatch\x12,\n" +
	"\apackets\x18\x01 \x03(\v2\x12.capture.v1.PacketR\apackets\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06pod_ip\x18\x03 \x01(\tR\x05podIp\"h\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\".\n" +
	"\rTsharkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\" \n" +
	"\x0eTsharkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x93\x01\n" +
	"\x0eCaptureService\x12;\n" +
	"\rStreamPackets\x12\x17.capture.v1.PacketBatch\x1a\x0f.capture.v1.Ack(\x01\x12D\n" +
	"\tSubscribe\x12\x1c.capture.v1.SubscribeRequest\x1a\x17.capture.v1.PacketBatch0\x012\xdf\x01\n" +
	"\x13CaptureAgentControl\x12E\n" +
	"\fEnableTshark\x12\x19.capture.v1.TsharkRequest\x1a\x1a.capture.v1.TsharkResponse\x12F\n" +
	"\rDisableTshark\x12\x19.capture.v1.TsharkRequest\x1a\x1a.capture.v1.TsharkResponse\x129\n" +
	"\x04Ping\x12\x17.capture.v1.PingRequest\x1a\x18.capture.v1.PingResponseB6Z4github.com/lpoclin/coach5g/api-server/internal/pb;pbb\x06proto3"

var (
	file_capture_proto_rawDescOnce sync.Once
	file_capture_proto_rawDescData []byte
)

func file_capture_proto_rawDescGZIP() []byte {
	file_capture_proto_rawDescOnce.Do(func() {
		file_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capture_proto_rawDesc), len(file_capture_proto_rawDesc)))
	})
	return file_capture_proto_rawDescData
}

var file_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_capture_proto_goTypes = []any{
	(*Packet)(nil),           // 0: capture.v1.Packet
	(*PacketBatch)(nil),      // 1: capture.v1.PacketBatch
	(*SubscribeRequest)(nil), // 2: capture.v1.SubscribeRequest
	(*Ack)(nil),              // 3: capture.v1.Ack
	(*TsharkRequest)(nil),    // 4: capture.v1.TsharkRequest
	(*TsharkResponse)(nil),   // 5: capture.v1.TsharkResponse
	(*PingRequest)(nil),      // 6: capture.v1.PingRequest
	(*PingResponse)(nil),     // 7: capture.v1.PingResponse
}
var file_capture_proto_depIdxs = []int32{
	0, // 0: capture.v1.PacketBatch.packets:type_name -> capture.v1.Packet
	1, // 1: capture.v1.CaptureService.StreamPackets:input_type -> capture.v1.PacketBatch
	2, // 2: capture.v1.CaptureService.Subscribe:input_type -> capture.v1.SubscribeRequest
	4, // 3: capture.v1.CaptureAgentControl.EnableTshark:input_type -> capture.v1.TsharkRequest
	4, // 4: capture.v1.CaptureAgentControl.DisableTshark:input_type -> capture.v1.TsharkRequest
	6, // 5: capture.v1.CaptureAgentControl.Ping:input_type -> capture.v1.PingRequest
	3, // 6: capture.v1.CaptureService.StreamPackets:output_type -> capture.v1.Ack
	1, // 7: capture.v1.CaptureService.Subscribe:output_type -> capture.v1.PacketBatch
	5, // 8: capture.v1.CaptureAgentControl.EnableTshark:output_type -> capture.v1.TsharkResponse
	5, // 9: capture.v1.CaptureAgentControl.DisableTshark:output_type -> capture.v1.TsharkResponse
	7, // 10: capture.v1.CaptureAgentControl.Ping:output_type -> capture.v1.PingResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capture_proto_init() }
func file_capture_proto_init() {
	if File_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capture_proto_rawDesc), len(file_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_capture_proto_goTypes,
		DependencyIndexes: file_capture_proto_depIdxs,
		MessageInfos:      file_capture_proto_msgTypes,
	}.Build()
	File_capture_proto = out.File
	file_capture_proto_goTypes = nil
	file_capture_proto_depIdxs = nil
}
