// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: capture.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptureService_StreamPackets_FullMethodName = "/capture.v1.CaptureService/StreamPackets"
	CaptureService_Subscribe_FullMethodName     = "/capture.v1.CaptureService/Subscribe"
)

// CaptureServiceClient is the client API for CaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureService is served by the api-server gRPC endpoint (:9999).
// capture-agent is the client that pushes batches; the frontend WebSocket
// handler subscribes to fan-out via Server.Subscribe().
type CaptureServiceClient interface {
	// StreamPackets: capture-agent -> api-server (client-streaming)
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, Ack], error)
	// Subscribe: api-server -> caller (server-streaming), used internally
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketBatch], error)
}

type captureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureServiceClient(cc grpc.ClientConnInterface) CaptureServiceClient {
	return &captureServiceClient{cc}
}

func (c *captureServiceClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PacketBatch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureService_ServiceDesc.Streams[0], CaptureService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PacketBatch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsClient = grpc.ClientStreamingClient[PacketBatch, Ack]

func (c *captureServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureService_ServiceDesc.Streams[1], CaptureService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PacketBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_SubscribeClient = grpc.ServerStreamingClient[PacketBatch]

// CaptureServiceServer is the server API for CaptureService service.
// All implementations must embed UnimplementedCaptureServiceServer
// for forward compatibility.
//
// CaptureService is served by the api-server gRPC endpoint (:9999).
// capture-agent is the client that pushes batches; the frontend WebSocket
// handler subscribes to fan-out via Server.Subscribe().
type CaptureServiceServer interface {
	// StreamPackets: capture-agent -> api-server (client-streaming)
	StreamPackets(grpc.ClientStreamingServer[PacketBatch, Ack]) error
	// Subscribe: api-server -> caller (server-streaming), used internally
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PacketBatch]) error
	mustEmbedUnimplementedCaptureServiceServer()
}

// UnimplementedCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureServiceServer struct{}

func (UnimplementedCaptureServiceServer) StreamPackets(grpc.ClientStreamingServer[PacketBatch, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedCaptureServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[PacketBatch]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCaptureServiceServer) mustEmbedUnimplementedCaptureServiceServer() {}
func (UnimplementedCaptureServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServiceServer will
// result in compilation errors.
type UnsafeCaptureServiceServer interface {
	mustEmbedUnimplementedCaptureServiceServer()
}

func RegisterCaptureServiceServer(s grpc.ServiceRegistrar, srv CaptureServiceServer) {
	// If the following call panics, it indicates UnimplementedCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureService_ServiceDesc, srv)
}

func _CaptureService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CaptureServiceServer).StreamPackets(&grpc.GenericServerStream[PacketBatch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsServer = grpc.ClientStreamingServer[PacketBatch, Ack]

func _CaptureService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptureServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, PacketBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_SubscribeServer = grpc.ServerStreamingServer[PacketBatch]

// CaptureService_ServiceDesc is the grpc.ServiceDesc for CaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capture.v1.CaptureService",
	HandlerType: (*CaptureServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _CaptureService_StreamPackets_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _CaptureService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capture.proto",
}

const (
	CaptureAgentControl_EnableTshark_FullMethodName  = "/capture.v1.CaptureAgentControl/EnableTshark"
	CaptureAgentControl_DisableTshark_FullMethodName = "/capture.v1.CaptureAgentControl/DisableTshark"
	CaptureAgentControl_Ping_FullMethodName          = "/capture.v1.CaptureAgentControl/Ping"
)

// CaptureAgentControlClient is the client API for CaptureAgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptureAgentControl is served by capture-agent (:9998).
// api-server calls this to enable/disable tshark on demand.
type CaptureAgentControlClient interface {
	EnableTshark(ctx context.Context, in *TsharkRequest, opts ...grpc.CallOption) (*TsharkResponse, error)
	DisableTshark(ctx context.Context, in *TsharkRequest, opts ...grpc.CallOption) (*TsharkResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type captureAgentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureAgentControlClient(cc grpc.ClientConnInterface) CaptureAgentControlClient {
	return &captureAgentControlClient{cc}
}

func (c *captureAgentControlClient) EnableTshark(ctx context.Context, in *TsharkRequest, opts ...grpc.CallOption) (*TsharkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TsharkResponse)
	err := c.cc.Invoke(ctx, CaptureAgentControl_EnableTshark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureAgentControlClient) DisableTshark(ctx context.Context, in *TsharkRequest, opts ...grpc.CallOption) (*TsharkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TsharkResponse)
	err := c.cc.Invoke(ctx, CaptureAgentControl_DisableTshark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureAgentControlClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CaptureAgentControl_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureAgentControlServer is the server API for CaptureAgentControl service.
// All implementations must embed UnimplementedCaptureAgentControlServer
// for forward compatibility.
//
// CaptureAgentControl is served by capture-agent (:9998).
// api-server calls this to enable/disable tshark on demand.
type CaptureAgentControlServer interface {
	EnableTshark(context.Context, *TsharkRequest) (*TsharkResponse, error)
	DisableTshark(context.Context, *TsharkRequest) (*TsharkResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedCaptureAgentControlServer()
}

// UnimplementedCaptureAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureAgentControlServer struct{}

func (UnimplementedCaptureAgentControlServer) EnableTshark(context.Context, *TsharkRequest) (*TsharkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableTshark not implemented")
}
func (UnimplementedCaptureAgentControlServer) DisableTshark(context.Context, *TsharkRequest) (*TsharkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableTshark not implemented")
}
func (UnimplementedCaptureAgentControlServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCaptureAgentControlServer) mustEmbedUnimplementedCaptureAgentControlServer() {}
func (UnimplementedCaptureAgentControlServer) testEmbeddedByValue()                             {}

// UnsafeCaptureAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureAgentControlServer will
// result in compilation errors.
type UnsafeCaptureAgentControlServer interface {
	mustEmbedUnimplementedCaptureAgentControlServer()
}

func RegisterCaptureAgentControlServer(s grpc.ServiceRegistrar, srv CaptureAgentControlServer) {
	// If the following call panics, it indicates UnimplementedCaptureAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureAgentControl_ServiceDesc, srv)
}

func _CaptureAgentControl_EnableTshark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsharkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureAgentControlServer).EnableTshark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureAgentControl_EnableTshark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureAgentControlServer).EnableTshark(ctx, req.(*TsharkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureAgentControl_DisableTshark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsharkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureAgentControlServer).DisableTshark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureAgentControl_DisableTshark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureAgentControlServer).DisableTshark(ctx, req.(*TsharkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureAgentControl_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureAgentControlServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureAgentControl_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureAgentControlServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptureAgentControl_ServiceDesc is the grpc.ServiceDesc for CaptureAgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureAgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capture.v1.CaptureAgentControl",
	HandlerType: (*CaptureAgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableTshark",
			Handler:    _CaptureAgentControl_EnableTshark_Handler,
		},
		{
			MethodName: "DisableTshark",
			Handler:    _CaptureAgentControl_DisableTshark_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CaptureAgentControl_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capture.proto",
}
